import React, { useEffect, useRef, useState } from "react";
import { Link, useLocation, useNavigate } from "react-router-dom";
import {
  ArrowUpRight,
  ArrowRight,
  Wallet,
  Mail,
  User,
  KeyRound,
  Plus,
  Trash2,
  Download,
  Copy,
  LogOut,
  RefreshCw,
  Check,
  ShieldCheck,
  Coins,
  Clock,
  ExternalLink,
} from "lucide-react";
import {
  api,
  useApp,
  Button,
  ErrorBox,
  CopyButton,
  Modal,
  fmt,
  date,
  walletSign,
  PageTitle,
  Footer,
  Empty,
} from "./lib";