export const faqs = [
  [
    "What is Anonyma?",
    "One prepaid workspace for AI chat, coding, images and video. Choose a model and pay for the requests you make. Browser and API share the same credit balance.",
  ],
  [
    "Do I need a subscription?",
    "No. Add credits when you need them. There is no recurring subscription or minimum monthly usage.",
  ],
  [
    "How do I pay?",
    "Choose an amount and a supported cryptocurrency in your account. Your invoice gives you the exact amount, network and address. Credits arrive after the payment processor confirms the payment. Payments must be connected before funding is available.",
  ],
  [
    "What models are available?",
    "Browse the live catalog for provider, price, context and capability details. Workspace availability is shown separately from catalog listings. You can switch models in a conversation; a vision-capable model is required for image references.",
  ],
  [
    "How much does it cost?",
    "1,000 credits equal $1. Each model has its own usage rate; see the estimate before a request and the receipt afterward. Rejected requests and empty outputs release their reservation. Partial output can incur a charge, and the documented timeout policy may charge the reserved amount.",
  ],
  [
    "Is my data private?",
    "Saved chats and media are private to your account. Model providers receive prompts when you generate content. This is not end-to-end encryption or a promise of universal zero retention. Export or delete your content from your account.",
  ],
  [
    "Do my credits expire?",
    "No. Unused credits remain in your account and work across the browser workspace and your API keys. Credits and optional tokens are separate; holding tokens does not create a credit balance.",
  ],
];
export const docSections = [
  {
    id: "getting-started",
    title: "Getting started",
    group: "Start here",
    summary: "From first sign-in to your first answer.",
    body: [
      [
        "One balance, every model",
        "Create an account with a username and password, email verification, or a signed wallet message. Username accounts do not require an email; add a verified recovery email later. Add prepaid credits, select a callable model, and send your first prompt.",
      ],
      [
        "Credits and reservations",
        "1,000 credits equal $1. Before a request begins, the service reserves enough for the estimated input and maximum output. The remaining amount becomes available when the actual usage is settled. A reservation is not a second charge.",
      ],
      [
        "Local test mode",
        "When the top banner says LOCAL TEST MODE, the installation uses test credits and deterministic integration fixtures. Outputs are not generated by real models and credits have no monetary value. Payments are disabled.",
      ],
    ],
  },
  {
    id: "workspace",
    title: "The workspace",
    group: "Use Anonyma",
    summary: "Ask, code, images, video, history and attachments.",
    body: [
      [
        "Ask and code",
        "Send prompts, switch models without abandoning the conversation, stop a response, copy Markdown, and inspect the receipt. The code panel extracts fenced code blocks into downloadable files and preserves their message versions. It does not execute generated code.",
      ],
      [
        "Images and vision",
        "Attach PNG, JPEG, WebP or GIF references to a compatible vision model, up to eight images. Generate one to four images or compare several image models. Open, download, rerun or delete saved images from the library. Arbitrary PDFs and documents are not supported uploads.",
      ],
      [
        "Video",
        "Choose a model, duration, quality and aspect ratio. Submit a prompt and optionally a public image URL. Video jobs persist if you close the page. Pending costs remain reserved until completion or a known failure. Unknown submission outcomes require operator reconciliation to avoid a duplicate charge.",
      ],
      [
        "History and privacy",
        "The latest 300 conversations, 100 images and 60 videos are retained per account. Export conversations before deleting them. Signed temporary API media links expire after one day; workspace files remain private until you delete them or they age out of the retention count.",
      ],
    ],
  },
  {
    id: "credits",
    title: "Credits & billing",
    group: "Use Anonyma",
    summary: "Prepaid balance, estimates and usage receipts.",
    body: [
      [
        "What you pay",
        "The service quotes provider rates and any configured platform markup. Token utility affects markup only. Input tokens, output tokens and provider-billed reasoning can contribute to cost. Maximum-output estimates are ceilings, not predictions of response length.",
      ],
      [
        "Failed and interrupted requests",
        "Empty output produces an error without a charge. An explicit upstream rejection is free. Canceling a stream can still incur a debit for partial output, calculated from reported usage or an estimate when final usage is missing. Unreadable provider responses and upstream timeouts charge the full reservation under the failure-billing policy; inspect activity before retrying. Unknown video submissions are held for reconciliation.",
      ],
      [
        "Deposits",
        "The payment processor supplies a supported-currency list, exact invoice amount, receiving address and status. Send only the specified asset/network and amount. Finished, verified invoices are credited once. Underpayments, expired invoices and refunds require processor/operator review; credit withdrawals are not supported.",
      ],
    ],
  },
  {
    id: "api",
    title: "API reference",
    group: "Developers",
    summary: "OpenAI-compatible chat completions and streaming.",
    body: [
      [
        "Endpoints",
        "GET /v1 is a free connection check. GET /v1/models requires a key and lists callable chat/image models without pricing. POST /v1/chat/completions accepts model, messages, max_tokens and stream. GET /v1/balance is a convenience extension for the CLI.",
      ],
      [
        "Limits",
        "Only system, user and assistant roles are accepted. Only string content is used; array content is skipped. The latest 40 usable messages are sent, with a 120,000-character and 256 KB JSON body limit. max_tokens defaults to 4,096; larger values are clamped to 8,192. Request timeout is 120 seconds; 120 requests/minute per IP. Availability and balance checks happen before provider execution.",
      ],
      [
        "Compatibility boundaries",
        "Unknown optional parameters are ignored. Do not depend on tool calling, JSON-schema structured outputs, embeddings, audio, search, Files, Assistants, Responses, fine-tuning or cross-origin browser calls. Compatible clients must use ordinary chat-completions mode.",
      ],
      [
        "Receipts and streaming",
        "SSE sends OpenAI-style delta chunks, a final usage chunk containing askr.credits_charged and anonyma.credits_charged, then [DONE]. Image-capable upstreams may emit delta.images. Use a unique Idempotency-Key per logical request; duplicate submissions return 409.",
      ],
    ],
  },
  {
    id: "keys",
    title: "API keys & spending caps",
    group: "Developers",
    summary: "Create, protect, limit and revoke access.",
    body: [
      [
        "Create a key",
        "Account → API keys → Create. Copy the secret immediately: only its cryptographic hash is stored. A user can have 20 active keys and create 10 keys per hour. Keep keys on a server, never in public frontend source.",
      ],
      [
        "Rolling limits",
        "An optional credit cap includes successful spend in the previous 24 hours plus all active reservations. A request is rejected if its worst-case reservation would exceed the cap. The window is rolling, not a midnight reset.",
      ],
      [
        "Revocation",
        "Revoke a key from your account. Subsequent authenticated requests immediately fail. A request already accepted may finish and settle its reserved usage. Keys have no separate scopes, team roles or automatic expiry.",
      ],
    ],
  },
  {
    id: "cli",
    title: "Command line",
    group: "Developers",
    summary: "Install, configure and chat from the terminal.",
    body: [
      [
        "Installation",
        "The CLI runs on Node 18 or later. Download /cli.mjs, inspect it, and run node cli.mjs. The /install.sh and /install.ps1 scripts provide optional local installation. No global npm package or paid subscription is required.",
      ],
      [
        "Configuration",
        "Run anonyma config to save the API base URL and key in ~/.config/anonyma/config.json with restricted permissions. ANONYMA_API_KEY and ANONYMA_BASE_URL override saved values. Never pass your secret key as a positional command argument.",
      ],
      [
        "Commands",
        "/models lists available models; /model ID selects one; /new clears local conversation context; /balance shows spendable credits; /exit quits. Pass a quoted prompt for a one-shot request. The interactive session streams Markdown and displays the usage receipt.",
      ],
    ],
  },
  {
    id: "integrations",
    title: "SDKs & integrations",
    group: "Developers",
    summary: "Connect existing chat-completions clients.",
    body: [
      [
        "OpenAI SDKs",
        "Set base_url to your installation origin plus /v1 and api_key to your Anonyma key. Use chat.completions.create. Node and Python examples are provided below. Do not use Responses API or function-calling examples.",
      ],
      [
        "Editors and assistants",
        "Continue, Aider, Cursor, Open WebUI, LangChain and LlamaIndex can be configured with an OpenAI-compatible endpoint where their ordinary chat mode is available. Features that require tools, embeddings or vendor-specific routes are not compatible. Client-specific settings vary; no automatic account linking is provided.",
      ],
    ],
  },
  {
    id: "wallets",
    title: "Wallets & token utility",
    group: "Account",
    summary: "Signatures, linked wallets and holding tiers.",
    body: [
      [
        "Wallet sign-in",
        "The server issues a single-use nonce with this site’s domain, chain, issue time and expiration. Sign the message in your wallet to prove control. Signing in does not initiate a blockchain transfer. One wallet can be linked to one account.",
      ],
      [
        "Optional token",
        "The installation operator must configure an actual ERC20 token contract and matching RPC before wallet holdings can be checked. Tokens are not credits. Any discount reduces platform markup only; with zero markup there is no extra monetary discount.",
      ],
      [
        "Discount calculation",
        "For each 1% of the one-billion reference supply held, platform markup is reduced by 25%, capped at 100%. There is no minimum holding duration for this calculation. The reference's separate 14-day benefit concerns early access to newly released models, not waiting to earn a discount. Early model access and priority routing are not yet active on this installation.",
      ],
    ],
  },
  {
    id: "security",
    title: "Security & privacy",
    group: "Account",
    summary: "How your credentials and saved content are handled.",
    body: [
      [
        "Authentication",
        "Passwords are scrypt-hashed with a unique salt. Session tokens and API secrets are stored as hashes. Session cookies are HttpOnly, SameSite=Lax, and Secure on HTTPS. Wallet challenges and email codes expire and are single-use.",
      ],
      [
        "Stored data",
        "SQLite stores account identifiers, conversations, usage, reservations and a financial audit ledger. Private generated files live outside the public assets folder. Owner checks protect every conversation and library route. Upstream providers receive the content needed to serve your request.",
      ],
      [
        "Export and closure",
        "Export your profile, ledger and conversations from Account. Deleting an account revokes sessions/keys and removes saved chats/media. Financial records retain a tombstoned account identifier for audit, so account deletion does not erase settled ledger entries.",
      ],
    ],
  },
  {
    id: "errors",
    title: "Errors & troubleshooting",
    group: "Help",
    summary: "Understand failures and recover safely.",
    body: [
      [
        "401 / 402 / 429",
        "401 means missing/expired authentication or a revoked key. 402 means available credits cannot cover the reservation. 429 means a request rate or API-key spending cap was exceeded. Do not retry a rejected cap endlessly.",
      ],
      [
        "503 / provider unavailable",
        "The gateway, email service or payment processor may not be configured on this installation. The catalog includes unavailable and planned models; only models explicitly marked runnable can be selected for generation.",
      ],
      [
        "Duplicate request / uncertain video",
        "409 duplicate_request protects against reusing an idempotency key. If a video says reconciliation, do not blindly resubmit it. The operator must inspect its upstream status before settling or releasing the hold.",
      ],
      [
        "Contact",
        "Use the Support page to save a request for this installation’s operator. Configured email/Telegram links provide additional contact options. Include the request or invoice ID, never your password, API key or wallet seed phrase.",
      ],
    ],
  },
];
export const articles = [
  {
    slug: "one-balance-many-models",
    title: "One balance. Many models.",
    category: "Guide",
    intro: "How a prepaid gateway fits into your AI workflow.",
    paragraphs: [
      "Subscriptions reserve a fixed budget for one provider each month. A prepaid gateway instead charges individual requests against a shared balance. It can be useful for switching between specialized models or for irregular workloads.",
      "Compare the rates and capabilities of the models you actually use. A cheap input-token price does not automatically mean a cheaper task: output length, reasoning tokens, retries and image or video generation all affect the final bill.",
      "Prepaid access does not reproduce every feature of a provider’s consumer subscription. Bundled tools, proprietary search, file systems and editorial integrations may differ. Use the calculator as a usage estimate, not a promise of equal service.",
    ],
  },
  {
    slug: "choose-an-ai-model",
    title: "Choosing the right model",
    category: "Learn",
    intro: "Match capabilities, context and price to the task.",
    paragraphs: [
      "Start with modality: text, image or video. For a text conversation with pictures, select a vision-capable chat model. A model visible in a broad upstream catalog is not necessarily executable through every endpoint.",
      "Context length describes the provider model, while the application also limits message count and request size. These limits protect both latency and cost. A large context number alone is not a reason to send every document on every turn.",
      "Compare two models with the same representative prompts and review their actual outputs. The comparison calculator estimates costs from supplied token counts; it does not measure factual accuracy, safety or creativity.",
    ],
  },
  {
    slug: "subscriptions-vs-usage",
    title: "Subscriptions vs. pay per use",
    category: "Comparison",
    intro: "A fair comparison starts with your workload.",
    paragraphs: [
      "A fixed subscription can be convenient for frequent interactive use, while usage billing lets a shared balance cover many model families. Neither pricing model is always cheaper.",
      "Estimate how many prompts you send and their typical input/output lengths. Then account for tasks beyond text: images and clips may be priced per generation and can dominate a small budget.",
      "The savings calculator compares selected monthly list prices against token-rate estimates. It does not include every bundled subscription benefit, possible provider discounts, taxes or cryptocurrency transfer fees.",
    ],
  },
  {
    slug: "openai-compatible-clients",
    title: "Bring your own AI client",
    category: "Developers",
    intro: "Use familiar SDKs with a different base URL.",
    paragraphs: [
      "An OpenAI-compatible chat endpoint lets existing clients send standard role/content messages with a model identifier. Set the base URL, create a server-side key and try a small request first.",
      "Compatibility is a subset, not an assurance that every vendor endpoint works. This service supports chat completions and streaming; it does not provide Responses, embeddings, tool calls or Assistants.",
      "Set a rolling key cap for each integration and revoke unused keys. Keep keys out of public browser bundles. Browser requests from third-party origins are intentionally not enabled.",
    ],
  },
  {
    slug: "crypto-deposits",
    title: "How prepaid crypto deposits work",
    category: "Guide",
    intro: "From an invoice to spendable credits.",
    paragraphs: [
      "Choose an amount and a cryptocurrency supported by the payment processor. Each invoice provides an exact amount and receiving address for the selected network. An invoice is not proof of payment.",
      "The processor watches the blockchain and sends a signed status notification. The service verifies the notification and credits a finished invoice only once, even if the processor retries the same callback.",
      "Transfer fees, minimums and confirmation times vary. Underpayments and expired invoices require review; avoid sending a second transfer to an old invoice without checking its status. Credits cannot be withdrawn as cryptocurrency.",
    ],
  },
];
export const roadmap = [
  [
    "Available",
    "Unified prepaid workspace",
    "Chat, code, images, durable video jobs, saved history, shared ledger and developer API.",
  ],
  [
    "Available",
    "Account controls",
    "Password, verified email, signed wallets, private library, exports and spending caps.",
  ],
  [
    "Planned",
    "Direct provider connections",
    "Additional native integrations, provider failover and richer routing controls.",
  ],
  [
    "Planned",
    "Audio tools",
    "Speech, transcription and music workflows beyond catalog discovery.",
  ],
  [
    "Planned",
    "Advanced context",
    "Shared memory, collaborative workspaces and model fusion.",
  ],
  [
    "Planned",
    "More control",
    "Reasoning controls, supported structured output and provider-specific retention options.",
  ],
  [
    "Planned",
    "Payment infrastructure",
    "Additional processors and transparent fee controls.",
  ],
  [
    "Research",
    "Token ecosystem",
    "Credit trading, withdrawals and buyback concepts have not been implemented or launched.",
  ],
];
