export const models = [
  {
    id: "openai/gpt-4.1",
    name: "GPT-4.1",
    provider: "OpenAI",
    type: "chat",
    color: "mint",
    icon: "✳",
    context_length: 1047576,
    vision: true,
    description: "A general-purpose model for writing, analysis and code.",
  },
  {
    id: "anthropic/claude-sonnet-4",
    name: "Claude Sonnet 4",
    provider: "Anthropic",
    type: "chat",
    color: "peach",
    icon: "✺",
    context_length: 200000,
    vision: true,
    description: "Reasoning, careful writing and software development.",
  },
  {
    id: "google/gemini-2.5-pro",
    name: "Gemini 2.5 Pro",
    provider: "Google",
    type: "chat",
    color: "lavender",
    icon: "✦",
    context_length: 1048576,
    vision: true,
    description: "Long-context reasoning and multimodal understanding.",
  },
  {
    id: "deepseek/deepseek-chat",
    name: "DeepSeek",
    provider: "DeepSeek",
    type: "chat",
    color: "sky",
    icon: "≈",
    context_length: 65536,
    description: "An alternative for everyday language and code tasks.",
  },
  {
    id: "google/gemini-2.5-flash-image",
    name: "Gemini Flash Image",
    provider: "Google",
    type: "image",
    imageCapable: true,
    vision: true,
    color: "yellow",
    icon: "▧",
    description: "Create and edit images with reference input.",
  },
  {
    id: "google/gemini-3-pro-image",
    name: "Gemini Pro Image",
    provider: "Google",
    type: "image",
    imageCapable: true,
    vision: true,
    color: "pink",
    icon: "◈",
    description: "An image workflow described in the product brief.",
  },
  {
    id: "video-pending-verification",
    name: "Video models",
    provider: "Provider catalog",
    type: "video",
    color: "mint",
    icon: "▷",
    description: "Provider inventory and supported options await verification.",
  },
].map((m) => ({
  ...m,
  callable: false,
  status: "catalog-only",
  pricing: null,
}));
export const capabilities = [
  {
    title: "Think & build",
    description: "From a first question to the next big idea.",
    items: [
      "Multi-model conversations",
      "A dedicated code workspace",
      "Saved history and revisions",
    ],
    icon: "chat",
    color: "mint",
    to: "/workspace/chat",
  },
  {
    title: "Create & explore",
    description: "Turn what you imagine into something you can see.",
    items: [
      "Image generation and comparison",
      "Reference-image inputs",
      "Asynchronous video workflows",
    ],
    icon: "image",
    color: "lavender",
    to: "/workspace/image",
  },
  {
    title: "Connect & control",
    description: "Your workspace. Your tools. One shared balance.",
    items: [
      "Usage-based prepaid credits",
      "Developer API and keys",
      "Clear receipts and account history",
    ],
    icon: "code",
    color: "yellow",
    to: "/developers",
  },
];
export const faqs = [
  [
    "What is ANONYMA?",
    "ANONYMA is a prepaid AI workspace designed to bring chat, code, image and video workflows together. Choose a supported model, use a shared credit balance and return to your saved work.",
  ],
  [
    "Do I need a separate subscription for each model?",
    "The product uses a shared prepaid balance instead of separate model subscriptions. Model rates and availability must be confirmed by the connected service before you generate.",
  ],
  [
    "How do credits work?",
    "The documented conversion is 1 USD = 1,000 credits. The service reserves an estimated amount before a request, settles the charge afterward and releases the unused reservation. Estimates are not invoices.",
  ],
  [
    "Can I use ANONYMA with my own tools?",
    "The planned integration supports a documented subset of OpenAI-compatible chat completions at /v1, using an ANONYMA customer API key. It does not imply support for every client, tools, embeddings or the Responses API.",
  ],
  [
    "What can I try in this preview?",
    "The interactive demo includes sample conversations, code export, illustrative image results and account controls stored in this browser. It does not contact AI providers, accept payments or create a production account.",
  ],
  [
    "Is my work private?",
    "The intended service restricts conversations and media to their account owner. This preview stores demo work only in this browser. Neither the preview nor the documented architecture provides end-to-end encryption.",
  ],
];
export const articles = [
  {
    slug: "choose-a-model",
    title: "The right model for the way you work.",
    tag: "MODEL GUIDE",
    color: "yellow",
    icon: "models",
    intro: "Start with the task, then choose the model.",
    body: [
      "Different tasks benefit from different strengths. For writing, compare clarity and tone. For code, examine correctness, explanation and how easily you can revise the result.",
      "Use the catalog to inspect capabilities and context limits. A catalog listing does not establish that a model is currently available to run. ANONYMA keeps availability separate from discovery.",
      "For images, select an image-capable model. Reference input additionally requires vision support. For video, duration, ratio and quality must come from the provider’s supported options.",
    ],
  },
  {
    slug: "understanding-credits",
    title: "A little more clarity. Every single credit.",
    tag: "CREDITS & USAGE",
    color: "mint",
    icon: "credits",
    intro: "Understand estimates, reservations and receipts.",
    body: [
      "The documented conversion is 1 USD to 1,000 displayed credits. Available credits exclude the portion reserved for work in progress.",
      "An estimate appears before generation. A final receipt reports the charge after completion. Interrupted work can still have a charge; stopping a request is not a guarantee of free usage.",
      "ANONYMA customer credits and the operator’s provider balance are separate systems. Real funding and usage remain unavailable in this standalone preview.",
    ],
  },
  {
    slug: "one-api",
    title: "One connection. More possibilities.",
    tag: "DEVELOPER NOTES",
    color: "lavender",
    icon: "code",
    intro: "Bring a supported chat workflow into your own tools.",
    body: [
      "Customer API keys belong to ANONYMA accounts. They are distinct from the operator’s upstream provider key, which must remain on the server.",
      "The documented API subset includes model listing, balance and chat completions. Check the client’s requirements before configuring it; tools, embeddings and the Responses API are outside this scope.",
      "Use the same account ledger for web and API usage. A key cap limits a particular key over a rolling 24-hour window; it is not a business-wide budget cap.",
    ],
  },
];
