import React, { useState, useMemo, useEffect } from "react";
import { Link, useParams, useSearchParams } from "react-router-dom";
import {
  ArrowUpRight,
  ArrowRight,
  Plus,
  Minus,
  Check,
  Search,
  SlidersHorizontal,
  ChevronDown,
  Copy,
  Download,
  Code2,
  MessageSquare,
  Image,
  Video,
  Wallet,
  Coins,
  LockKeyhole,
  Layers3,
  Shuffle,
  ExternalLink,
  BookOpen,
  Terminal,
  Braces,
  ShieldCheck,
} from "lucide-react";
import {
  useApp,
  PageTitle,
  Footer,
  Button,
  ProviderIcon,
  fmt,
  dollars,
  modelPrice,
  generationPrice,
  CopyButton,
  download,
  ErrorBox,
  api,
} from "./lib";